name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install dependencies
        run: yarn install

      - name: Deploy
        env:
          TUMBLR_API_END_POINT: ${{ vars.TUMBLR_API_END_POINT }}
          SPEAKER_DECK_API_END_POINT: ${{ vars.SPEAKER_DECK_API_END_POINT }}
        run: |
          git config --global user.email "land.front.high.field@gmail.com"
          git config --global user.name "asmz"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

          # Setup env file
          echo "EXPO_PUBLIC_TUMBLR_API_END_POINT=$TUMBLR_API_END_POINT" > .env
          echo "EXPO_PUBLIC_SPEAKER_DECK_API_END_POINT=$SPEAKER_DECK_API_END_POINT" >> .env

          yarn deploy
