name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/setup_ci

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feature/setup_ci

      - name: Install dependencies
        run: yarn install

      - name: Deploy
        run: yarn deploy
